<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "account_sendata".
 *
 * @property int $id
 * @property string $time_stamp
 * @property string $e
 * @property string $ax
 * @property string $ay
 * @property string $az
 * @property string $gx
 * @property string $gy
 * @property string $gz
 * @property string $mx
 * @property string $my
 * @property string $mz
 * @property string $lat
 * @property string $lng
 * @property string $p
 * @property string $s
 */
class AccountSendata extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'account_sendata';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['time_stamp', 'e', 'ax', 'ay', 'az', 'gx', 'gy', 'gz', 'mx', 'my', 'mz', 'lat', 'lng', 'p', 's'], 'required'],
            [['time_stamp', 'ax', 'ay', 'az', 'gx', 'gy', 'gz', 'mx', 'my', 'mz', 'lat', 'lng', 'p', 's'], 'string', 'max' => 20],
            [['e'], 'string', 'max' => 25],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'time_stamp' => Yii::t('app', 'Time Stamp'),
            'e' => Yii::t('app', 'E'),
            'ax' => Yii::t('app', 'Ax'),
            'ay' => Yii::t('app', 'Ay'),
            'az' => Yii::t('app', 'Az'),
            'gx' => Yii::t('app', 'Gx'),
            'gy' => Yii::t('app', 'Gy'),
            'gz' => Yii::t('app', 'Gz'),
            'mx' => Yii::t('app', 'Mx'),
            'my' => Yii::t('app', 'My'),
            'mz' => Yii::t('app', 'Mz'),
            'lat' => Yii::t('app', 'Lat'),
            'lng' => Yii::t('app', 'Lng'),
            'p' => Yii::t('app', 'P'),
            's' => Yii::t('app', 'S'),
        ];
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        //$this->time_stamp = $this->time_stamp / 1000;
        //$this->time_stamp = date('d/m/Y H:i:s.v', $this->time_stamp);
    }
}
